import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "saviynt/saviynt-enterprise-identity-cloud-api-reference",
    },
    {
      type: "category",
      label: "1.0 Authentication",
      link: {
        type: "doc",
        id: "saviynt/1-0-authentication",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/get-authorization-token",
          label: "Get Authorization Token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/refresh-authorization-token",
          label: "Refresh Authorization Token",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Users",
      link: {
        type: "doc",
        id: "saviynt/users",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-user",
          label: "Create User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-user",
          label: "Update User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/bulk-upload-users",
          label: "Bulk Upload Users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-user-details",
          label: "Get User Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-list-of-users",
          label: "Get List of Users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "saviynt/add-remove-user-from-sav-role",
          label: "Add/Remove User from SAV ROLE",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-access-details-for-user",
          label: "Get Access Details For User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-flat-response-entitlement-details-for-user",
          label: "Get Flat Response Entitlement Details For User",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "saviynt/get-flat-response-role-details-for-user",
          label: "Get Flat Response Role Details For User",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "saviynt/authenticate-user",
          label: "Authenticate User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/validate-user-data",
          label: "Validate User Data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-savroles",
          label: "Get SavRoles",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Accounts",
      link: {
        type: "doc",
        id: "saviynt/accounts",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/get-account-details",
          label: "Get Account Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/export-account",
          label: "Export Account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/create-account",
          label: "Create Account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-account",
          label: "Update Account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/assign-account-to-user",
          label: "Assign Account to User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/assign-entitlement-to-account",
          label: "Assign Entitlement to Account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/remove-entitlement-from-account",
          label: "Remove Entitlement from Account",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Entitlements",
      link: {
        type: "doc",
        id: "saviynt/entitlements",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-privilege",
          label: "Create Privilege",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/update-privilege",
          label: "Update Privilege",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/delete-privilege",
          label: "Delete Privilege",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/get-entitlements",
          label: "Get Entitlements",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-child-entitlements",
          label: "Get Child Entitlements",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "saviynt/create-update-entitlement",
          label: "Create/Update Entitlement",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-entitlement-values-for-endpoint",
          label: "Get Entitlement Values For Endpoint",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-list-of-privileges-for-entitlement-type",
          label: "Get List of Privileges for Entitlement Type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/remove-entitlement-from-role",
          label: "Remove Entitlement From Role",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Privileges",
      link: {
        type: "doc",
        id: "saviynt/privileges",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-privilege",
          label: "Create Privilege",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/update-privilege",
          label: "Update Privilege",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/delete-privilege",
          label: "Delete Privilege",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Roles",
      link: {
        type: "doc",
        id: "saviynt/roles",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/add-role",
          label: "Add Role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-role-details-for-user",
          label: "Get Role Details for user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-firefighter-role-details",
          label: "Get FireFighter Role Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/remove-role",
          label: "Remove Role",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Endpoints",
      link: {
        type: "doc",
        id: "saviynt/endpoints",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-endpoint",
          label: "Create Endpoint",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-endpoint",
          label: "Update Endpoint",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/get-list-of-endpoints",
          label: "Get List of Endpoints",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/create-entitlement-type",
          label: "Create Entitlement Type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-entitlement-type",
          label: "Update Entitlement Type",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/get-list-of-entitlement-types",
          label: "Get List of Entitlement Types",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "saviynt/create-dynamic-attribute",
          label: "Create Dynamic Attribute",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-dynamic-attribute",
          label: "Update Dynamic Attribute",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/fetch-dynamic-attributes",
          label: "Fetch Dynamic Attributes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "saviynt/delete-dynamic-attribute",
          label: "Delete Dynamic Attribute",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "saviynt/delete-entitlement-types",
          label: "Delete Entitlement Types",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Security Systems",
      link: {
        type: "doc",
        id: "saviynt/security-systems",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-security-system",
          label: "Create Security System",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-security-system",
          label: "Update Security System",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/get-list-of-security-systems",
          label: "Get List of Security Systems",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "saviynt/delete-security-system",
          label: "Delete Security System",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "User Groups",
      link: {
        type: "doc",
        id: "saviynt/user-groups",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-update-usergroup",
          label: "Create/Update UserGroup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/add-remove-user-from-usergroup",
          label: "Add/Remove User From UserGroup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/delete-usergroup",
          label: "Delete UserGroup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-list-of-usergroups",
          label: "Get List of UserGroups",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Organization",
      link: {
        type: "doc",
        id: "saviynt/organization",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-organization",
          label: "Create Organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-organization",
          label: "Update Organization",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/get-organization",
          label: "Get Organization",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "saviynt/delete-organization",
          label: "Delete Organization",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Connections",
      link: {
        type: "doc",
        id: "saviynt/connections",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/get-list-of-connections",
          label: "Get List of Connections",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-connections-details",
          label: "Get Connections Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/delete-connections",
          label: "Delete Connections",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Dataset",
      link: {
        type: "doc",
        id: "saviynt/dataset",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/createdataset",
          label: "createDataset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/getdatasetvalues",
          label: "getDatasetValues",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "saviynt/updatedatasetvalues",
          label: "updateDatasetValues",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/deletedataset",
          label: "deleteDataset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/uploaddatasetcsv",
          label: "uploadDatasetCSV",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/updatedataset",
          label: "updateDataset",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "3.0 Analytics",
      link: {
        type: "doc",
        id: "saviynt/3-0-analytics",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/fetch-list-of-analytics",
          label: "Fetch List of Analytics",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-analytics-details",
          label: "Fetch Analytics Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/run-analytics-controls",
          label: "Run Analytics Controls",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-runtime-controls-data",
          label: "Fetch Runtime Controls Data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-runtime-controls-data-v-2",
          label: "Fetch Runtime Controls Data V2",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-list-of-analytics-es",
          label: "Fetch List of Analytics ES",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "saviynt/fetch-control-attributes",
          label: "Fetch Control Attributes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-control-details-es",
          label: "Fetch Control Details ES",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "4.0 Access Request",
      link: {
        type: "doc",
        id: "saviynt/4-0-access-request",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-user-request",
          label: "Create User Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-user-request",
          label: "Update User Request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/get-requestable-users",
          label: "Get Requestable Users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "saviynt/create-role-request",
          label: "Create Role Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-role-request",
          label: "Update Role Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-user-requestable-entitlements",
          label: "Get User Requestable Entitlements",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/validate-entitlement-request-data",
          label: "Validate Entitlement Request Data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/request-to-create-entitlement-based-role",
          label: "Request to Create Entitlement Based Role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/create-organization-request",
          label: "Create Organization Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-organization-request",
          label: "Update Organization Request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/create-auto-approved-request",
          label: "Create Auto-approved Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/create-birthright-request",
          label: "Create Birthright Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/add-approver-to-existing-request",
          label: "Add Approver to existing Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-request-history-my-pending-requests",
          label: "Fetch Request History (my pending requests)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-request-history-details",
          label: "Fetch Request History Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/cancel-pending-request",
          label: "Cancel Pending Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-list-of-pending-requests-for-approver",
          label: "Get List of Pending Requests for Approver",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-request-approval-details",
          label: "Fetch Request Approval Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/approve-reject-each-line-item-in-a-request",
          label: "Approve/Reject each line item in a request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-pending-approvals",
          label: "Get Pending Approvals",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/approve-reject-entire-request",
          label: "Approve/Reject entire request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/create-task-remove-entitlement",
          label: "Create Task - Remove Entitlement",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/complete-single-task",
          label: "Complete Single Task",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-tasks",
          label: "Update Tasks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/discontinue-tasks",
          label: "Discontinue Tasks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/discontinue-all-pending-tasks",
          label: "Discontinue All Pending Tasks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-task-details",
          label: "Fetch Task Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-request-access-attributes",
          label: "Fetch Request Access Attributes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/check-task-status",
          label: "Check Task Status",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Create Request",
      link: {
        type: "doc",
        id: "saviynt/create-request",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-user-request",
          label: "Create User Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-user-request",
          label: "Update User Request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/get-requestable-users",
          label: "Get Requestable Users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "saviynt/create-role-request",
          label: "Create Role Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-role-request",
          label: "Update Role Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-user-requestable-entitlements",
          label: "Get User Requestable Entitlements",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/validate-entitlement-request-data",
          label: "Validate Entitlement Request Data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/request-to-create-entitlement-based-role",
          label: "Request to Create Entitlement Based Role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/create-organization-request",
          label: "Create Organization Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-organization-request",
          label: "Update Organization Request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/create-auto-approved-request",
          label: "Create Auto-approved Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/create-birthright-request",
          label: "Create Birthright Request",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Users1",
      link: {
        type: "doc",
        id: "saviynt/users-1",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-user-request",
          label: "Create User Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-user-request",
          label: "Update User Request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/get-requestable-users",
          label: "Get Requestable Users",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Roles1",
      link: {
        type: "doc",
        id: "saviynt/roles-1",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-role-request",
          label: "Create Role Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-role-request",
          label: "Update Role Request",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Entitlements1",
      link: {
        type: "doc",
        id: "saviynt/entitlements-1",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/get-user-requestable-entitlements",
          label: "Get User Requestable Entitlements",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/validate-entitlement-request-data",
          label: "Validate Entitlement Request Data",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Entitlement Based Role",
      link: {
        type: "doc",
        id: "saviynt/entitlement-based-role",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/request-to-create-entitlement-based-role",
          label: "Request to Create Entitlement Based Role",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Organization1",
      link: {
        type: "doc",
        id: "saviynt/organization-1",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-organization-request",
          label: "Create Organization Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-organization-request",
          label: "Update Organization Request",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Update Existing Request",
      link: {
        type: "doc",
        id: "saviynt/update-existing-request",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/add-approver-to-existing-request",
          label: "Add Approver to existing Request",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Request History",
      link: {
        type: "doc",
        id: "saviynt/request-history",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/fetch-request-history-my-pending-requests",
          label: "Fetch Request History (my pending requests)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-request-history-details",
          label: "Fetch Request History Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/cancel-pending-request",
          label: "Cancel Pending Request",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Request Approval",
      link: {
        type: "doc",
        id: "saviynt/request-approval",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/get-list-of-pending-requests-for-approver",
          label: "Get List of Pending Requests for Approver",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-request-approval-details",
          label: "Fetch Request Approval Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/approve-reject-each-line-item-in-a-request",
          label: "Approve/Reject each line item in a request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/get-pending-approvals",
          label: "Get Pending Approvals",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/approve-reject-entire-request",
          label: "Approve/Reject entire request",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Tasks",
      link: {
        type: "doc",
        id: "saviynt/tasks",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-task-remove-entitlement",
          label: "Create Task - Remove Entitlement",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/complete-single-task",
          label: "Complete Single Task",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-tasks",
          label: "Update Tasks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/discontinue-tasks",
          label: "Discontinue Tasks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/discontinue-all-pending-tasks",
          label: "Discontinue All Pending Tasks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-task-details",
          label: "Fetch Task Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-request-access-attributes",
          label: "Fetch Request Access Attributes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/check-task-status",
          label: "Check Task Status",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Create Task",
      link: {
        type: "doc",
        id: "saviynt/create-task",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-task-remove-entitlement",
          label: "Create Task - Remove Entitlement",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Update Task",
      link: {
        type: "doc",
        id: "saviynt/update-task",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/complete-single-task",
          label: "Complete Single Task",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/update-tasks",
          label: "Update Tasks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/discontinue-tasks",
          label: "Discontinue Tasks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/discontinue-all-pending-tasks",
          label: "Discontinue All Pending Tasks",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Task Details",
      link: {
        type: "doc",
        id: "saviynt/task-details",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/fetch-task-details",
          label: "Fetch Task Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-request-access-attributes",
          label: "Fetch Request Access Attributes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/check-task-status",
          label: "Check Task Status",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "5.0 Delegated Administration",
      link: {
        type: "doc",
        id: "saviynt/5-0-delegated-administration",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/get-delegate-user-list",
          label: "Get Delegate User List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "saviynt/create-delegate",
          label: "Create Delegate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-existing-delegates-list",
          label: "Fetch Existing Delegates List",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/edit-delegate",
          label: "Edit Delegate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/delete-delegate",
          label: "Delete Delegate",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "6.0 Attestations",
      link: {
        type: "doc",
        id: "saviynt/6-0-attestations",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/fetch-attestation-list",
          label: "Fetch Attestation List",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-attestation-details",
          label: "Fetch Attestation Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/certify-usermanager-requests",
          label: "Certify UserManager Requests",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-attestation-account-entitlement-details",
          label: "Fetch Attestation Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/approve-reject-attestation-account-details",
          label: "Approve Reject Attestation Account Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/lock-attestation",
          label: "Lock Attestation",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "7.0 Campaigns",
      link: {
        type: "doc",
        id: "saviynt/7-0-campaigns",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/fetch-campaign-list",
          label: "Fetch Campaign List",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-campaign-details",
          label: "Fetch Campaign Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/certify-user-manager-for-campaign",
          label: "Certify User Manager for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-account-entitlement-details",
          label: "Fetch Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/approve-reject-campaign-account-entitlement-details",
          label: "Approve Reject Campaign Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/lock-campaign",
          label: "Lock Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/reassign-usermanager-step-1-for-campaign",
          label: "Reassign UserManager Step 1 for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/consult-usermanager-step-1-for-campaign",
          label: "Consult UserManager Step 1 for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/consult-campaign-account-entitlement-details",
          label: "Consult Campaign Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/reassign-certification-at-account-and-entitlement-level-copy",
          label: "Reassign Certification at Account and Entitlement Level Copy",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/consult-entitlementowner-step-1-for-campaign",
          label: "Consult EntitlementOwner Step 1 for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/consult-entitlementowner-step-2-for-campaign",
          label: "Consult EntitlementOwner Step 2 for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-account-entitlement-details-1",
          label: "Fetch Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-entitlement-owner-campaign-details",
          label: "Fetch Entitlement Owner Campaign Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-flat-response-entitlement-owner-campaign-details",
          label: "Fetch Flat Response Entitlement Owner Campaign Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/lock-campaign-1",
          label: "Lock Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/approve-reject-account-entitlement-details",
          label: "Approve Reject Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/certify-entitlement-owner-for-campaign",
          label: "Certify Entitlement Owner for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/reassign-entitlement-owner-for-campaign",
          label: "Reassign Entitlement Owner for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/reassign-certification-at-account-level",
          label: "Reassign Certification at Account Level",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-account-entitlement-details-2",
          label: "Fetch Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/approve-reject-account-entitlement-details-1",
          label: "Approve Reject Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/lock-campaign-2",
          label: "Lock Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/consult-appowner-account-entitlement-details",
          label: "Consult AppOwner Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/reassign-application-owner-for-campaign",
          label: "Reassign Application Owner for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-certification-list",
          label: "Fetch Certification List",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/discontinue-campaigns-and-certifications",
          label: "Discontinue Campaigns and Certifications",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/reassign-certification",
          label: "Reassign Certification",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "User Manager",
      link: {
        type: "doc",
        id: "saviynt/user-manager",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/fetch-campaign-list",
          label: "Fetch Campaign List",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-campaign-details",
          label: "Fetch Campaign Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/certify-user-manager-for-campaign",
          label: "Certify User Manager for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-account-entitlement-details",
          label: "Fetch Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/approve-reject-campaign-account-entitlement-details",
          label: "Approve Reject Campaign Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/lock-campaign",
          label: "Lock Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/reassign-usermanager-step-1-for-campaign",
          label: "Reassign UserManager Step 1 for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/consult-usermanager-step-1-for-campaign",
          label: "Consult UserManager Step 1 for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/consult-campaign-account-entitlement-details",
          label: "Consult Campaign Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/reassign-certification-at-account-and-entitlement-level-copy",
          label: "Reassign Certification at Account and Entitlement Level Copy",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Entitlement Owner",
      link: {
        type: "doc",
        id: "saviynt/entitlement-owner",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/consult-entitlementowner-step-1-for-campaign",
          label: "Consult EntitlementOwner Step 1 for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/consult-entitlementowner-step-2-for-campaign",
          label: "Consult EntitlementOwner Step 2 for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-account-entitlement-details-1",
          label: "Fetch Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-entitlement-owner-campaign-details",
          label: "Fetch Entitlement Owner Campaign Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-flat-response-entitlement-owner-campaign-details",
          label: "Fetch Flat Response Entitlement Owner Campaign Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/lock-campaign-1",
          label: "Lock Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/approve-reject-account-entitlement-details",
          label: "Approve Reject Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/certify-entitlement-owner-for-campaign",
          label: "Certify Entitlement Owner for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/reassign-entitlement-owner-for-campaign",
          label: "Reassign Entitlement Owner for Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/reassign-certification-at-account-level",
          label: "Reassign Certification at Account Level",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Application Owner",
      link: {
        type: "doc",
        id: "saviynt/application-owner",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/fetch-account-entitlement-details-2",
          label: "Fetch Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/approve-reject-account-entitlement-details-1",
          label: "Approve Reject Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/lock-campaign-2",
          label: "Lock Campaign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/consult-appowner-account-entitlement-details",
          label: "Consult AppOwner Account Entitlement Details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/reassign-application-owner-for-campaign",
          label: "Reassign Application Owner for Campaign",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "8.0 Segregation of Duties",
      link: {
        type: "doc",
        id: "saviynt/8-0-segregation-of-duties",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/sod-evaluation-for-sap-functions",
          label: "SoD Evaluation for SAP Functions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/sod-evaluation-for-non-sap-functions",
          label: "SoD Evaluation for Non - SAP Functions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/add-mitigating-control-risk-account",
          label: "Add Mitigating Control Risk Account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/upload-sod-ruleset",
          label: "Upload SOD Ruleset",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "9.0 Password Reset",
      link: {
        type: "doc",
        id: "saviynt/9-0-password-reset",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/fetch-security-questions",
          label: "Fetch Security Questions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-user-security-questions",
          label: "Fetch User Security Questions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/validate-user-security-answers",
          label: "Validate User Security Answers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/create-security-questions",
          label: "Create Security Questions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/create-password-policy",
          label: "Create Password Policy",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/change-user-password",
          label: "Change User Password",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Using SQA",
      link: {
        type: "doc",
        id: "saviynt/using-sqa",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/fetch-security-questions",
          label: "Fetch Security Questions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-user-security-questions",
          label: "Fetch User Security Questions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/validate-user-security-answers",
          label: "Validate User Security Answers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/create-security-questions",
          label: "Create Security Questions",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Password Policy",
      link: {
        type: "doc",
        id: "saviynt/password-policy",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-password-policy",
          label: "Create Password Policy",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "10.0 Common Utilities",
      link: {
        type: "doc",
        id: "saviynt/10-0-common-utilities",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-and-update-trigger",
          label: "Create and Update Trigger",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/check-job-status",
          label: "Check Job Status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/delete-trigger",
          label: "Delete Trigger",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/run-job-trigger",
          label: "Run Job Trigger",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-job-metadata",
          label: "Fetch Job Metadata",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/createtrigger",
          label: "createTrigger",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/resumepausejobs",
          label: "resumePauseJobs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/upload-new-file",
          label: "Upload New File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/test-connection",
          label: "Test Connection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/import-application-data",
          label: "Import Application Data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/check-import-status",
          label: "Check Import Status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/force-complete",
          label: "Force Complete",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/send-email",
          label: "Send Email",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Job Control",
      link: {
        type: "doc",
        id: "saviynt/job-control",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/create-and-update-trigger",
          label: "Create and Update Trigger",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/check-job-status",
          label: "Check Job Status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/delete-trigger",
          label: "Delete Trigger",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/run-job-trigger",
          label: "Run Job Trigger",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/fetch-job-metadata",
          label: "Fetch Job Metadata",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/createtrigger",
          label: "createTrigger",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/resumepausejobs",
          label: "resumePauseJobs",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "File Directory",
      link: {
        type: "doc",
        id: "saviynt/file-directory",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/upload-new-file",
          label: "Upload New File",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "SAV",
      link: {
        type: "doc",
        id: "saviynt/sav",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/upload-new-file",
          label: "Upload New File",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "11.0 Dashboard",
      link: {
        type: "doc",
        id: "saviynt/11-0-dashboard",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/retrieve-dashboard-tiles-data",
          label: "Retrieve Dashboard Tiles Data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/retrieve-dashboard-account-data",
          label: "Retrieve Dashboard Account Data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/retrieve-dashboard-data",
          label: "Retrieve Dashboard Data",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "13.0 PAA",
      link: {
        type: "doc",
        id: "saviynt/13-0-paa",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/get-access-recommendations",
          label: "Get Access Recommendations",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "14.0 Transport",
      link: {
        type: "doc",
        id: "saviynt/14-0-transport",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/export-package",
          label: "Export Package",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/import-package",
          label: "Import Package",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/transport-status",
          label: "Transport Status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "15.0 Policies",
      link: {
        type: "doc",
        id: "saviynt/15-0-policies",
      },
      items: [
        {
          type: "doc",
          id: "saviynt/fetch-technical-rules",
          label: "Fetch Technical Rules",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "saviynt/update-technical-rules",
          label: "Update Technical Rules",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "saviynt/create-technical-rules",
          label: "Create Technical Rules",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "saviynt/delete-technical-rules",
          label: "Delete Technical Rules",
          className: "api-method delete",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
