/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Saviynt OpenAPI Docs",
  "tagline": "OpenAPI plugin for generating API reference docs in Docusaurus v2",
  "url": "https://kkundan.github.io",
  "baseUrl": "/",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "api-editor",
  "projectName": "api-editor.github.io",
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "/",
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/tree/main/demo",
          "docItemComponent": "@theme/ApiItem"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "gtag": {
          "trackingID": "GTM-THVM29S",
          "anonymizeIP": false
        }
      }
    ]
  ],
  "themeConfig": {
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "title": "APIs",
      "logo": {
        "alt": "Keytar",
        "src": "img/Saviynt_logo_Navy.svg"
      },
      "items": [
        {
          "type": "dropdown",
          "label": "Version",
          "position": "left",
          "items": [
            {
              "label": "5.0",
              "to": "/category/saviynt-api"
            },
            {
              "label": "Beta",
              "to": "/category/saviynt-api"
            }
          ]
        },
        {
          "href": "https://docs.saviyntcloud.com/",
          "position": "right",
          "className": "header-medium-link",
          "aria-label": "Saviynt Docs"
        },
        {
          "href": "https://saviynt.github.io",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "OpenAPI Docs",
              "to": "/"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/docusaurus"
            },
            {
              "label": "Discord",
              "href": "https://discordapp.com/invite/docusaurus"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/docusaurus"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "href": "https://medium.com/palo-alto-networks-developer-blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/PaloAltoNetworks/docusaurus-openapi-docs"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2024 Palo Alto Networks, Inc. Built with Docusaurus 3.1.1."
    },
    "prism": {
      "additionalLanguages": [
        "ruby",
        "csharp",
        "php",
        "java",
        "powershell",
        "json",
        "bash"
      ],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "languageTabs": [
      {
        "highlight": "bash",
        "language": "curl",
        "logoClass": "bash"
      },
      {
        "highlight": "python",
        "language": "python",
        "logoClass": "python",
        "variant": "requests"
      },
      {
        "highlight": "go",
        "language": "go",
        "logoClass": "go"
      },
      {
        "highlight": "javascript",
        "language": "nodejs",
        "logoClass": "nodejs",
        "variant": "axios"
      },
      {
        "highlight": "ruby",
        "language": "ruby",
        "logoClass": "ruby"
      },
      {
        "highlight": "csharp",
        "language": "csharp",
        "logoClass": "csharp",
        "variant": "httpclient"
      },
      {
        "highlight": "php",
        "language": "php",
        "logoClass": "php"
      },
      {
        "highlight": "java",
        "language": "java",
        "logoClass": "java",
        "variant": "unirest"
      },
      {
        "highlight": "powershell",
        "language": "powershell",
        "logoClass": "powershell"
      }
    ],
    "algolia": {
      "apiKey": "441074cace987cbf4640c039ebed303c",
      "appId": "J0EABTYI1A",
      "indexName": "docusaurus-openapi",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "announcementBar": {
      "id": "announcementBar_1",
      "content": "Beta preview that adds support for Docusaurus v3.0.0",
      "isCloseable": true
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "plugins": [
    [
      "docusaurus-plugin-openapi-docs",
      {
        "id": "openapi",
        "docsPluginId": "classic",
        "config": {
          "petstore_versioned": {
            "specPath": "examples/petstore.yaml",
            "outputDir": "docs/petstore_versioned",
            "sidebarOptions": {
              "groupPathsBy": "tag",
              "categoryLinkSource": "tag"
            },
            "version": "2.0.0",
            "label": "v2.0.0",
            "baseUrl": "/petstore_versioned/swagger-petstore-yaml",
            "versions": {
              "1.0.0": {
                "specPath": "examples/petstore-1.0.0.yaml",
                "outputDir": "docs/petstore_versioned/1.0.0",
                "label": "v1.0.0",
                "baseUrl": "/petstore_versioned/1.0.0/swagger-petstore-yaml"
              }
            }
          },
          "petstore": {
            "specPath": "examples/petstore.yaml",
            "proxy": "https://cors.pan.dev",
            "outputDir": "docs/petstore",
            "sidebarOptions": {
              "groupPathsBy": "tag",
              "categoryLinkSource": "tag"
            },
            "template": "api.mustache",
            "downloadUrl": "https://raw.githubusercontent.com/PaloAltoNetworks/docusaurus-openapi-docs/main/demo/examples/petstore.yaml",
            "hideSendButton": false,
            "showSchemas": true
          },
          "cos": {
            "specPath": "examples/openapi-cos.json",
            "outputDir": "docs/cos",
            "sidebarOptions": {
              "groupPathsBy": "tag"
            }
          },
          "burgers": {
            "specPath": "examples/food/burgers/openapi.yaml",
            "outputDir": "docs/food/burgers"
          },
          "yogurt": {
            "specPath": "examples/food/yogurtstore/openapi.yaml",
            "outputDir": "docs/food/yogurtstore"
          },
          "restaurant": {
            "specPath": "examples/food/restaurant/openapi.yaml",
            "outputDir": "docs/restaurant",
            "sidebarOptions": {
              "groupPathsBy": "tagGroup"
            }
          },
          "saviynt": {
            "specPath": "examples/saviynt-eic-api_openapi3.yaml",
            "outputDir": "docs/saviynt",
            "sidebarOptions": {
              "groupPathsBy": "tag",
              "categoryLinkSource": "tag"
            }
          }
        }
      }
    ]
  ],
  "themes": [
    "docusaurus-theme-openapi-docs"
  ],
  "stylesheets": [
    {
      "href": "https://use.fontawesome.com/releases/v5.11.0/css/all.css",
      "type": "text/css"
    }
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
